version: '2'

services:

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_MONGO=true
                - INSTALL_XDEBUG=false
                - INSTALL_NODE=true
                - COMPOSER_GLOBAL_INSTALL=true
                - PUID=1000
                - PGID=1000
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP
            # this will be appended to /etc/hosts
            # Note that this IP can perhaps be better injected via .env
            - "dockerhost:172.17.0.1"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_MONGO=true
                - INSTALL_XDEBUG=false
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_MEMCACHED=false
            dockerfile: Dockerfile-70
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP
            # this will be appended to /etc/hosts
            # Note that this IP can perhaps be better injected via .env
            - "dockerhost:172.17.0.1"
        environment:
            # IMPORTANT: You must have a Remote Interpreter entry matching this name
            # In settings, search for interpreter...
            # PHP > Languages & Frameworks > PHP > Interpreter > click on [...]
            # Need to have a Remote Interpreter named 'laravel'
            - PHP_IDE_CONFIG="serverName=laravel"

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### MongoDB Container #######################################

    mongo:
        build: ./mongo
        ports:
            - "27017:27017"
        volumes_from:
            - volumes_data

### Redis Container #########################################

    redis:
        build: ./redis
        volumes_from:
            - volumes_data
        ports:
            - "6379:6379"

### Laravel Application Code Container ######################

    volumes_source:
        build: ./volumes/application
        volumes:
            - ../src:/var/www/laravel

### Databases Data Container ################################

    volumes_data:
        build: ./volumes/data
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/redis:/data
            - ./data/mongo:/data/db

### Add more Containers below ###############################
